var artists = [
  {
    Name: "Owlcity",
    cover: "assets/music/Owl City/artist.jpg",
    banner: "assets/music/Owl City/banner.jpg",
    albums: [],
    songs: [
      {
        name: "Cave In",
        artist: "Owl City",
        album: "Ocean Eyes",
        src: "assets/music/Owl City/Ocean Eyes/1.mp3",
        cover: "assets/music/Owl City/Ocean Eyes/cover.jpg",
      },
      {
        name: "Hello Seattle",
        artist: "Owl City",
        album: "Ocean Eyes",
        src: "assets/music/Owl City/Ocean Eyes/1.mp3",
        cover: "assets/music/Owl City/Ocean Eyes/cover.jpg",
      },
      {
        name: "The Saltwater Room",
        artist: "Owl City",
        album: "Ocean Eyes",
        src: "assets/music/Owl City/Ocean Eyes/1.mp3",
        cover: "assets/music/Owl City/Ocean Eyes/cover.jpg",
      },
      {
        name: "Fireflies",
        artist: "Owl City",
        album: "Ocean Eyes",
        src: "assets/music/Owl City/Ocean Eyes/1.mp3",
        cover: "assets/music/Owl City/Ocean Eyes/cover.jpg",
      },
      {
        name: "Vanila Twilight",
        artist: "Owl City",
        album: "Ocean Eyes",
        src: "assets/music/Owl City/Ocean Eyes/1.mp3",
        cover: "assets/music/Owl City/Ocean Eyes/cover.jpg",
      },
      {
        name: "Hot Air Balloon",
        artist: "Owl City",
        album: "Ocean Eyes",
        src: "assets/music/Owl City/Ocean Eyes/1.mp3",
        cover: "assets/music/Owl City/Ocean Eyes/cover.jpg",
      },
    ],
  },
  {
    Name: "Linkin Park",
    cover: "assets/music/Linkin Park/artist.jpg",
    banner: "assets/music/Linkin Park/banner.jpg",
    albums: [],
    songs: [
      {
        name: "Lost in Echo",
        artist: "Linkin Park",
        album: "Living Things",
        src: "assets/music/Linkin Park/Living Things/1.mp3",
        cover: "assets/music/Linkin Park/Living Things/cover.jpg",
      },
      {
        name: "Victimized",
        artist: "Linkin Park",
        album: "Living Things",
        src: "assets/music/Linkin Park/Living Things/1.mp3",
        cover: "assets/music/Linkin Park/Living Things/cover.jpg",
      },
      {
        name: "Roads Untraveled",
        artist: "Linkin Park",
        album: "Living Things",
        src: "assets/music/Linkin Park/Living Things/1.mp3",
        cover: "assets/music/Linkin Park/Living Things/cover.jpg",
      },
      {
        name: "Skin To Bone",
        artist: "Linkin Park",
        album: "Living Things",
        src: "assets/music/Linkin Park/Living Things/1.mp3",
        cover: "assets/music/Linkin Park/Living Things/cover.jpg",
      },
      {
        name: "Tinfoil",
        artist: "Linkin Park",
        album: "Living Things",
        src: "assets/music/Linkin Park/Living Things/1.mp3",
        cover: "assets/music/Linkin Park/Living Things/cover.jpg",
      },
      {
        name: "Powerless",
        artist: "Linkin Park",
        album: "Living Things",
        src: "assets/music/Linkin Park/Living Things/1.mp3",
        cover: "assets/music/Linkin Park/Living Things/cover.jpg",
      },
      {
        name: "Valentine's Day",
        artist: "Linkin Park",
        album: "Minutes To Midnight",
        src: "assets/music/Linkin Park/Minutes To Midnight/1.mp3",
        cover: "assets/music/Linkin Park/Minutes To Midnight/cover.jpg",
      },
      {
        name: "In Pieces",
        artist: "Linkin Park",
        album: "Minutes To Midnight",
        src: "assets/music/Linkin Park/Minutes To Midnight/1.mp3",
        cover: "assets/music/Linkin Park/Minutes To Midnight/cover.jpg",
      },
      {
        name: "Leave Out All The Rest",
        artist: "Linkin Park",
        album: "Minutes To Midnight",
        src: "assets/music/Linkin Park/Minutes To Midnight/1.mp3",
        cover: "assets/music/Linkin Park/Minutes To Midnight/cover.jpg",
      },
      {
        name: "What I've Done",
        artist: "Linkin Park",
        album: "Minutes To Midnight",
        src: "assets/music/Linkin Park/Minutes To Midnight/1.mp3",
        cover: "assets/music/Linkin Park/Minutes To Midnight/cover.jpg",
      },
    ],
  },
  {
    Name: "Paramore",
    cover: "assets/music/Paramore/artist.jpg",
    banner: "assets/music/Paramore/banner.jpg",
    albums: [],
    songs: [
      {
        name: "Decode",
        artist: "Paramore",
        album: "Brand New Eyes",
        src: "assets/music/Paramore/Brand New Eyes/1.mp3",
        cover: "assets/music/Paramore/Brand New Eyes/cover.jpg",
      },
      {
        name: "Monster",
        artist: "Paramore",
        album: "Brand New Eyes",
        src: "assets/music/Paramore/Brand New Eyes/1.mp3",
        cover: "assets/music/Paramore/Brand New Eyes/cover.jpg",
      },
      {
        name: "Ignorance",
        artist: "Paramore",
        album: "Brand New Eyes",
        src: "assets/music/Paramore/Brand New Eyes/1.mp3",
        cover: "assets/music/Paramore/Brand New Eyes/cover.jpg",
      },
      {
        name: "Still Into You",
        artist: "Paramore",
        album: "Brand New Eyes",
        src: "assets/music/Paramore/Brand New Eyes/1.mp3",
        cover: "assets/music/Paramore/Brand New Eyes/cover.jpg",
      },
      {
        name: "Crush Crush Crush",
        artist: "Paramore",
        album: "Brand New Eyes",
        src: "assets/music/Paramore/Brand New Eyes/1.mp3",
        cover: "assets/music/Paramore/Brand New Eyes/cover.jpg",
      },
    ],
  },
  {
    Name: "Imagine Dragons",
    cover: "assets/music/Imagine Dragons/artist.jpg",
    banner: "assets/music/Imagine Dragons/banner.jpg",
    albums: [],
    songs: [
      {
        name: "It's Time",
        src: "assets/music/Imagine Dragons/Night Visions/1.mp3",
        cover: "assets/music/Imagine Dragons/Night Visions/cover.jpg",
        artist: "Imagine Dragons",
        album: "Night Visions",
      },
      {
        name: "Radioactive",
        src: "assets/music/Imagine Dragons/Night Visions/1.mp3",
        cover: "assets/music/Imagine Dragons/Night Visions/cover.jpg",
        artist: "Imagine Dragons",
        album: "Night Visions",
      },
      {
        name: "Demons",
        src: "assets/music/Imagine Dragons/Night Visions/1.mp3",
        cover: "assets/music/Imagine Dragons/Night Visions/cover.jpg",
        artist: "Imagine Dragons",
        album: "Night Visions",
      },
      {
        name: "Monster",
        src: "assets/music/Imagine Dragons/Night Visions/1.mp3",
        cover: "assets/music/Imagine Dragons/Night Visions/cover.jpg",
        artist: "Imagine Dragons",
        album: "Night Visions",
      },
    ],
  },
  {
    Name: "Avicii",
    cover: "assets/music/Avicii/artist.jpg",
    banner: "assets/music/Avicii/banner.jpg",
    albums: [],
    songs: [
      {
        name: "You Make Me",
        artist: "Avicii",
        album: "True",
        src: "assets/music/Avicii/True/1.mp3",
        cover: "assets/music/Avicii/True/cover.jpg",
      },
      {
        name: "Hey Brother",
        artist: "Avicii",
        album: "True",
        src: "assets/music/Avicii/True/1.mp3",
        cover: "assets/music/Avicii/True/cover.jpg",
      },
      {
        name: "Addicted To You",
        artist: "Avicii",
        album: "True",
        src: "assets/music/Avicii/True/1.mp3",
        cover: "assets/music/Avicii/True/cover.jpg",
      },
      {
        name: "Wake Me Up",
        artist: "Avicii",
        album: "True",
        src: "assets/music/Avicii/True/1.mp3",
        cover: "assets/music/Avicii/True/cover.jpg",
      },
    ],
  },
];
